### ISSUE TITLE
SchoolsController causes infinite loop due to lacking x-total-count header

### ISSUE THREAD

**Issue by ajtowf** [OfficeDev/O365-EDU-SDS-AspNetMVC-Samples#5]
Many controller actions lacks to include the response count as a response header (x-total-count), which causes SDS to get stuck in an infinite loop by increasing the offset.

    ?limit=100&offset=35000

Bad implementation of the sync from MS part imho, they shoul detect that the same response is returned for the 1000nd time.

Needed to add:

    IQuery<T> foos = ...
    foos = ApplyBinding(foos);
    ...
    return JsonOk(serializer.Finish(), ResponseCount);

to many actions to get a successful sync, but then finally in the SDS portal:

![image](https://user-images.githubusercontent.com/3427270/44623138-daf13800-a8c7-11e8-84cc-8e920dbfc7fa.png)

**Comment by gregorypilar** [comment]
Hi,

@ajtowf did you know exactly witch controller need to be modified?
